DROP PROCEDURE IF EXISTS GET_PROPERTIES_MINE;
DELIMITER $$
CREATE PROCEDURE GET_PROPERTIES_MINE()
BEGIN
    DECLARE V_SESSION JSON;
    DECLARE V_USER_ID BIGINT;

    SET V_SESSION =APP_SESSION();
    IF V_SESSION IS NULL THEN
        SELECT APP_ERROR();
    END IF;

    SET V_USER_ID=JSON_VALUE(V_SESSION,'$.user_id');

    SET @q=CONCAT('SELECT * FROM properties where user_id=',V_USER_ID);

    PREPARE stmt FROM @q;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;

END $$
DELIMITER ;

