DROP FUNCTION IF EXISTS USER_DETAIL;
DELIMITER $$
CREATE FUNCTION USER_DETAIL() RETURNS JSON
BEGIN
    DECLARE V_USER_ID BIGINT;
    DECLARE V_FULL_NAME VARCHAR(128);
    DECLARE V_EMAIL VARCHAR(64);
    DECLARE V_TYPE BIGINT DEFAULT 0;
    DECLARE V_PHONE VARCHAR(16);
    DECLARE V_SESSION JSON;
    DECLARE V_PAYLOAD JSON;

    SET V_SESSION = APP_SESSION();
    IF V_SESSION IS NULL THEN
        RETURN APP_ERROR();
    END IF;


    SET V_USER_ID = JSON_VALUE(V_SESSION, '$.user_id');

    SELECT name, email, type, phone
    INTO V_FULL_NAME,V_EMAIL,V_TYPE,V_PHONE
    FROM users
    WHERE id = V_USER_ID;

    SET V_PAYLOAD = JSON_OBJECT(
        'full_name', V_FULL_NAME,
        'email', V_EMAIL,
        'phone', V_PHONE,
        'type', V_TYPE,
        'user_id', V_USER_ID
                    );

    RETURN APP_RETURN(TRUE, 1037, V_PAYLOAD);

END$$
DELIMITER ;
