DROP FUNCTION IF EXISTS APP_RETURN;
DELIMITER $$
CREATE FUNCTION `APP_RETURN`(
    `P_STATUS` BOOL,
    `P_MESSAGECODE` BIGINT UNSIGNED,
    `P_DATA` JSON
) RETURNS JSON
    NO SQL
    DETERMINISTIC
BEGIN

  DECLARE V_MESSAGE TEXT;
  DECLARE V_STATUSCODE INT(5) UNSIGNED;

SELECT message, statusCode INTO V_MESSAGE, V_STATUSCODE FROM `site_messages` WHERE code = P_MESSAGECODE;

RETURN JSON_OBJECT(
    'status', P_STATUS,
    'data', P_DATA,
    'message', V_MESSAGE,
    'messageCode', P_MESSAGECODE,
    'code', V_STATUSCODE
       );

END$$
DELIMITER ;
