DROP FUNCTION IF EXISTS APP_SESSION;
DELIMITER $$
CREATE FUNCTION `APP_SESSION`(
) RETURNS JSON
    NOT DETERMINISTIC
BEGIN

    SET @userSession = IFNULL(@userSession, NULL);
    RETURN @userSession;

END$$
DELIMITER ;
